# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kothasaikrishna
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sendEmail

provider:
  name: aws
  runtime: python3.12
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
plugins:
  - serverless-offline
functions:
  hello:
    handler: handler.hello
    timeout: 30
    events:
      - httpApi:
          path: send-email
          method: post
